app:
  authentication:
    jwt:
      regular:
        secret: 321b963cf05e1b2d9af721754e56cc67170a92813b7630761229fd1179f6aa77
        expiration: 86400000
        header: Authorization
        prefix: Bearer
        type: JWT
      service:
        secret: GnlOnUAHvySgK9RgBik2qReWtyiP6m+1wDN4lq141p0=
        expiration: 86400000
        header: Authorization
        prefix: Bearer
        type: JWT
  gateway:
    core-service:
      target-url: http://localhost:8080
    authentication-service:
      target-url: http://localhost:8082

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.exadel.gateway: DEBUG
    org.springframework.security: DEBUG

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://localhost:8080
          predicates:
            - Path=/core-service/**
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/authentication-service/**

server:
  port: 8081