spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/core_database
    username: leonan
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: drop-and-create
    show-sql: true

server:
  port: 8080