services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'

  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: core_database
      POSTGRES_USER: leonan
      POSTGRES_PASSWORD: 123456
    ports:
      - '5435:5432'
    volumes:
      - core_postgres_data:/var/lib/postgresql/data

volumes:
  core_postgres_data: